main: com.cavetale.server.ServerPlugin

name: Server
version: 0.1
description: Server Plugin
api-version: 1.19

author: StarTux
website: https://github.com/StarTux/Server

depend: [Core, Connect, Mytems, SQL, Title]
softdepend: []

commands:

  server:
    aliases: []
    description: Warp to server
    permission: server.server
    usage: '/server <name>'

  serveradmin:
    aliases: [serveradm]
    description: Admin command
    permission: server.admin
    usage: '/serveradmin'

  who:
    aliases: [ list, ls, online ]
    permission: server.who
    description: List players on all servers
    usage: /who

  back:
    aliases: []
    permission: server.back
    description: Return to your last survival location
    usage: /back

permissions:

  server.server:
    description: Use /server
    default: op

  server.locked:
    description: Visit locked servers
    default: op

  server.hidden:
    description: See hidden servers
    default: op

  server.admin:
    description: Use /serveradmin
    default: op

  server.visit.*:
    description: Visit any server
    default: false

  server.who:
    description: Use /who
    default: op

  server.back:
    description: Use /back
    default: op